import { mkdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import type { AppContext } from './app.js'

/**
 * The `.dinah/` derivatives.
 *
 * The framework owns the entry (premise 3), and it owns it by *writing* it into
 * the application on every run rather than by smuggling it in as virtual
 * modules. The application still authors only `dinah.config.ts` and `src/`;
 * everything here is generated, git-ignored, and overwritten without warning.
 *
 * Writing real files buys one thing that decides the design: `@dinah/workbench`
 * and `react` resolve by name from the application's own `node_modules`,
 * because the importer physically lives there. Nothing has to be aliased into
 * existence, and no framework source enters the application's module graph.
 */
const JS_BANNER = '// Generated by dinah. Do not edit — this file is rewritten on every run.'
const HTML_BANNER = '<!-- Generated by dinah. Do not edit — this file is rewritten on every run. -->'

export interface GeneratedFiles {
  /** Vite root and HTML entry. */
  html: string
  /** Renderer entry the HTML loads. */
  renderer: string
  /** Electron main entry — the file the runtime process starts from. */
  main: string
  /** The tsconfig that typechecks the application. */
  tsconfig: string
}

/** Write `.dinah/` and return the paths worth naming afterwards. */
export function generate(app: AppContext): GeneratedFiles {
  mkdirSync(app.generatedDir, { recursive: true })

  const files: GeneratedFiles = {
    html: join(app.generatedDir, 'index.html'),
    renderer: join(app.generatedDir, 'renderer.tsx'),
    main: join(app.generatedDir, 'main.mjs'),
    tsconfig: join(app.generatedDir, 'tsconfig.json'),
  }

  write(files.html, indexHtml(app))
  write(files.renderer, rendererEntry())
  write(files.main, mainEntry())
  write(files.tsconfig, tsconfig())
  write(join(app.generatedDir, 'config.ts'), configModule(app))
  write(join(app.generatedDir, 'env.d.ts'), ambientTypes())

  return files
}

function write(path: string, contents: string): void {
  writeFileSync(path, contents.endsWith('\n') ? contents : `${contents}\n`, 'utf8')
}

function indexHtml(app: AppContext): string {
  return `${HTML_BANNER}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${escapeHtml(app.config.productName)}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="./renderer.tsx"></script>
  </body>
</html>`
}

function rendererEntry(): string {
  return `${JS_BANNER}
import { mountWorkbench } from '@dinah/workbench'
import '@dinah/workbench/style.css'
import { config } from './config'

mountWorkbench({ config })`
}

/**
 * The application's resolved config, as a module the renderer can import.
 * Defaults are already applied — resolution happened once, in the CLI.
 */
function configModule(app: AppContext): string {
  return `${JS_BANNER}
import type { ResolvedDinahConfig } from 'dinah'

export const config: ResolvedDinahConfig = ${JSON.stringify(app.config, null, 2)}`
}

/**
 * Electron's entry point. A bare specifier, because `.dinah/` sits inside the
 * application and Node's resolution walks up to the application's own
 * `node_modules` — the same lookup the packaged app performs.
 */
function mainEntry(): string {
  return `${JS_BANNER}
import '@dinah/runtime-electron/main'`
}

/**
 * The tsconfig that checks the application.
 *
 * Two things here are load-bearing and were paid for once already:
 *
 * - `types: []`. Naming `vite/client` fails with TS2688, because Vite is the
 *   *framework's* dependency and is not resolvable from the application. The
 *   ambient `*.css` declaration in `env.d.ts` replaces the one thing the
 *   application needed from it.
 * - Every root is listed explicitly. TypeScript's wildcards skip dot-directories,
 *   so a file in `.dinah/` reached only by a wildcard is checked by nothing at
 *   all — silently.
 */
function tsconfig(): string {
  // JSONC: tsconfig accepts comments, so the banner rides along with the file
  // it warns about instead of needing a key TypeScript would not recognise.
  return `${JS_BANNER}\n${JSON.stringify(
    {
      compilerOptions: {
        target: 'ES2023',
        lib: ['ES2023', 'DOM', 'DOM.Iterable'],
        module: 'ESNext',
        moduleResolution: 'bundler',
        jsx: 'react-jsx',
        types: [],
        strict: true,
        noUncheckedIndexedAccess: true,
        noImplicitOverride: true,
        exactOptionalPropertyTypes: true,
        isolatedModules: true,
        verbatimModuleSyntax: true,
        resolveJsonModule: true,
        skipLibCheck: true,
        forceConsistentCasingInFileNames: true,
        noEmit: true,
      },
      include: ['./env.d.ts', './config.ts', './renderer.tsx', '../dinah.config.ts', '../src'],
    },
    null,
    2,
  )}`
}

function ambientTypes(): string {
  return `${JS_BANNER}
// Stands in for \`vite/client\`, which the application cannot resolve: Vite is
// the framework's dependency, not the application's.
declare module '*.css'`
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}
