import { existsSync, mkdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import type { AppContext } from './app.js'

/**
 * The `.cheshire/` derivatives.
 *
 * The framework owns the entry (premise 3), and it owns it by *writing* it into
 * the application on every run rather than by smuggling it in as virtual
 * modules. The application still authors only `cheshire.config.ts` and `src/`;
 * everything here is generated, git-ignored, and overwritten without warning.
 *
 * Writing real files buys one thing that decides the design: `@cheshire/shell`
 * and `react` resolve by name from the application's own `node_modules`,
 * because the importer physically lives there. Nothing has to be aliased into
 * existence, and no framework source enters the application's module graph.
 */
const JS_BANNER = '// Generated by cheshire. Do not edit — this file is rewritten on every run.'
const HTML_BANNER = '<!-- Generated by cheshire. Do not edit — this file is rewritten on every run. -->'

export interface GeneratedFiles {
  /** Vite root and HTML entry. */
  html: string
  /** Renderer entry the HTML loads. */
  renderer: string
  /** Electron entry for `cheshire dev` — options arrive through the environment. */
  devMain: string
  /** Electron entry for a packaged app — options are baked in; this one is bundled. */
  prodMain: string
  /** The tsconfig that typechecks the application. */
  tsconfig: string
}

/** Write `.cheshire/` and return the paths worth naming afterwards. */
export function generate(app: AppContext): GeneratedFiles {
  mkdirSync(app.generatedDir, { recursive: true })

  const prodDir = join(app.generatedDir, 'prod')
  mkdirSync(prodDir, { recursive: true })

  const files: GeneratedFiles = {
    html: join(app.generatedDir, 'index.html'),
    renderer: join(app.generatedDir, 'renderer.tsx'),
    devMain: join(app.generatedDir, 'main.mjs'),
    prodMain: join(prodDir, 'main.mjs'),
    tsconfig: join(app.generatedDir, 'tsconfig.json'),
  }

  write(files.html, indexHtml(app))
  write(files.renderer, rendererEntry(hasAppEntry(app)))
  write(files.devMain, devMainEntry())
  write(files.prodMain, prodMainEntry(app))
  write(files.tsconfig, tsconfig())
  write(join(app.generatedDir, 'config.ts'), configModule(app))
  write(join(app.generatedDir, 'env.d.ts'), ambientTypes())

  return files
}

function write(path: string, contents: string): void {
  writeFileSync(path, contents.endsWith('\n') ? contents : `${contents}\n`, 'utf8')
}

function indexHtml(app: AppContext): string {
  return `${HTML_BANNER}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${escapeHtml(app.config.productName)}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="./renderer.tsx"></script>
  </body>
</html>`
}

/**
 * The renderer entry, and the join between the two halves of the program: the
 * framework's shell on one side, `../src/index` — the application's own entry —
 * on the other. This import is the only place the framework reads application
 * code, and it is a plain relative import because `.cheshire/` lives inside the
 * application.
 *
 * An application without an entry still runs. Deleting `src/index.ts` is a
 * mistake, but it is not a reason to hand the developer a module-resolution
 * failure from a file they did not write.
 */
function rendererEntry(hasEntry: boolean): string {
  return `${JS_BANNER}
import { mountShell } from '@cheshire/shell'
import '@cheshire/shell/style.css'
import { config } from './config'
${hasEntry ? `import app from '../src/index'` : 'const app = {} // no src/index.ts — nothing contributed'}

mountShell({ config, app })`
}

/** `src/index.ts` or `src/index.tsx` — either resolves for TypeScript and Vite. */
function hasAppEntry(app: AppContext): boolean {
  return ['index.ts', 'index.tsx'].some((name) => existsSync(join(app.root, 'src', name)))
}

/**
 * The application's resolved config, as a module the renderer can import.
 * Defaults are already applied — resolution happened once, in the CLI.
 */
function configModule(app: AppContext): string {
  return `${JS_BANNER}
import type { ResolvedCheshireConfig } from '@cheshire/app'

export const config: ResolvedCheshireConfig = ${JSON.stringify(app.config, null, 2)}`
}

/**
 * Electron's entry point in development. A bare specifier resolves because
 * `.cheshire/` sits inside the application, and Node walks up to the application's
 * own `node_modules`.
 *
 * The dev server's address is not known when this file is written — the port is
 * settled at listen time — so the options arrive through the environment rather
 * than baked in, as they are in the production entry.
 */
function devMainEntry(): string {
  return `${JS_BANNER}
import { start } from '@cheshire/runtime-electron/main'

start(JSON.parse(process.env.CHESHIRE_RUNTIME_OPTIONS))`
}

/**
 * Electron's entry point in a packaged application, and the reason the main
 * process is bundled at all.
 *
 * A packaged app ships **no `node_modules`**: this file is bundled with the
 * runtime inlined, leaving only `electron` and node builtins external. That is
 * what lets the application declare `cheshire` as a *dev* dependency and never
 * name the runtime (premise 5) — nothing has to be resolvable at runtime except
 * what Electron itself provides.
 *
 * The renderer is found relative to this file, since the bundle and the built
 * renderer are siblings inside the asar.
 */
function prodMainEntry(app: AppContext): string {
  return `${JS_BANNER}
import { fileURLToPath } from 'node:url'
import { start } from '@cheshire/runtime-electron/main'

start({
  config: ${JSON.stringify(app.config, null, 2)},
  rendererDir: fileURLToPath(new URL('../renderer', import.meta.url)),
})`
}

/**
 * The tsconfig that checks the application.
 *
 * Two things here are load-bearing and were paid for once already:
 *
 * - `types: []`. Naming `vite/client` fails with TS2688, because Vite is the
 *   *framework's* dependency and is not resolvable from the application. The
 *   ambient `*.css` declaration in `env.d.ts` replaces the one thing the
 *   application needed from it.
 * - Every root is listed explicitly. TypeScript's wildcards skip dot-directories,
 *   so a file in `.cheshire/` reached only by a wildcard is checked by nothing at
 *   all — silently.
 */
function tsconfig(): string {
  // JSONC: tsconfig accepts comments, so the banner rides along with the file
  // it warns about instead of needing a key TypeScript would not recognise.
  return `${JS_BANNER}\n${JSON.stringify(
    {
      compilerOptions: {
        target: 'ES2023',
        lib: ['ES2023', 'DOM', 'DOM.Iterable'],
        module: 'ESNext',
        moduleResolution: 'bundler',
        jsx: 'react-jsx',
        types: [],
        strict: true,
        noUncheckedIndexedAccess: true,
        noImplicitOverride: true,
        exactOptionalPropertyTypes: true,
        isolatedModules: true,
        verbatimModuleSyntax: true,
        resolveJsonModule: true,
        skipLibCheck: true,
        forceConsistentCasingInFileNames: true,
        noEmit: true,
      },
      include: ['./env.d.ts', './config.ts', './renderer.tsx', '../cheshire.config.ts', '../src'],
    },
    null,
    2,
  )}`
}

function ambientTypes(): string {
  return `${JS_BANNER}
// Stands in for \`vite/client\`, which the application cannot resolve: Vite is
// the framework's dependency, not the application's.
declare module '*.css'`
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}
